---


- block:
    - name: Ensure Gitlab Runner image is pulled
      docker_image:
        name: "{{ gitlab_runner_container_image }}"
        source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

    - name: Ensure Gitlab Runner paths exist
      file:
        path: "{{ item }}"
        state: directory
        mode: 0700
        owner: "{{ gitlab_gitlab_uid }}"
        group: "{{ gitlab_gitlab_gid }}"
      with_items:
        - "{{ gitlab_runner_base_path }}"
        - "{{ gitlab_runner_config_path }}"

    - name: Ensure gitlab-runner configuration installed
      template:
        src: "{{ role_path }}/templates/gitlab-runner/config.toml.j2"
        dest: "{{ gitlab_runner_config_path }}/config.toml"
        mode: 0644

    - name: Ensure gitlab-runner.service installed
      template:
        src: "{{ role_path }}/templates/gitlab-runner/gitlab-runner.service.j2"
        dest: "/etc/systemd/system/gitlab-runner.service"
        mode: 0644
      register: gitlab_runner_systemd_service_result

    - name: Ensure systemd reloaded after gitlab-runner.service installation
      service:
        daemon_reload: yes
      when: gitlab_runner_systemd_service_result.changed
  when: gitlab_runner_enabled|bool

- block:
    - name: Check existence of gitlab-runner service
      stat:
        path: "/etc/systemd/system/gitlab-runner.service"
      register: gitlab_runner_service_stat

    - name: Ensure gitlab-runner is stopped
      service:
        name: gitlab-runner
        state: stopped
        daemon_reload: yes
      register: stopping_result
      when: gitlab_runner_service_stat.stat.exists

    - name: Ensure gitlab-runner.service doesn't exist
      file:
        path: "/etc/systemd/system/gitlab-runner.service"
        state: absent
      when: gitlab_runner_service_stat.stat.exists

    - name: Ensure systemd reloaded after gitlab-runner.service removal
      service:
        daemon_reload: yes
      when: gitlab_runner_service_stat.stat.exists

    - name: Ensure Gitlab Runner directory removed
      file:
        path: "{{ gitlab_runner_base_path }}"
        state: absent
  when: not gitlab_runner_enabled
