---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Gitlab services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ gitlab_services_list }}"

- name: Ensure Gitlab services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ gitlab_services_list }}"
