---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: overseerr_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_overseerr.yml"
  when: overseerr_installation_enabled|bool == true
  tags:
    - setup-overseerr
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: overseerr_installation_enabled|bool == true
  tags:
    - start
