---

- name: Ensure Overseerr image is pulled
  docker_image:
    name: "{{ overseerr_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Overseerr paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ overseerr_data_path }}"

- name: Ensure overseerr.service installed
  template:
    src: "{{ role_path }}/templates/overseerr/overseerr.service.j2"
    dest: "/etc/systemd/system/overseerr.service"
    mode: 0644
  register: overseerr_systemd_service_result

- name: Ensure systemd reloaded after overseerr.service installation
  service:
    daemon_reload: yes
  when: overseerr_systemd_service_result.changed