---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Overseerr services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ overseerr_services_list }}"

- name: Ensure Overseerr services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ overseerr_services_list }}"