---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: grafana_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_grafana.yml"
  when: grafana_installation_enabled|bool == true
  tags:
    - setup-grafana
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: grafana_installation_enabled|bool == true
  tags:
    - start
