---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Grafana services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ grafana_services_list }}"

- name: Ensure Grafana services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ grafana_services_list }}"