- hosts: home_server
  roles:
    - { role: server-base }
    - { role: raid }
    - { role: nginx-proxy }
    - { role: gitlab }
    - { role: samba }
    - { role: transmission }
    - { role: plex }
    - { role: homepage }
    - { role: filebrowser }
    - { role: pihole }
    - { role: ps3netsrv }
    - { role: speedtest-tracker }
    - { role: sonarr }
    - { role: radarr }
    - { role: jackett }
    - { role: overseerr }
    - { role: tvheadend }
    - { role: metube }
    - { role: nexus }
    - { role: prometheus }
    - { role: grafana }
    - { role: postgres }
    - { role: pgadmin }