---

# We use an official nginx image, which we fix-up to run unprivileged.
# An alternative would be an `nginxinc/nginx-unprivileged` image, but
# those as more frequently out of date.
nginx_proxy_docker_image: "docker.io/nginx:1.23.0-alpine"

# A list of extra arguments to pass to the container
nginx_proxy_container_extra_arguments: []

nginx_proxy_base_path: "{{ base_data_path }}/nginx-proxy"
nginx_proxy_data_path: "{{ nginx_proxy_base_path }}/data"
nginx_proxy_confd_path: "{{ nginx_proxy_base_path }}/conf.d"


nginx_services_list: |
  {{
    (['nginx-proxy.service'])
  }}