---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Torrserver services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ torrserver_services_list }}"

- name: Ensure Torrserver services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ torrserver_services_list }}"