---

# `docker_network` doesn't work as expected when the given network
# is a substring of a network that already exists.
#
# See:
# - https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/12
# - https://github.com/ansible/ansible/issues/32926
#
# Due to that, we employ a workaround below.
#
# - name: Ensure Nginx-proxy network is created in Docker
#   docker_network:
#     name: "{{ nginx_docker_network }}"
#     driver: bridge
- name: Check existence of Nginx-proxy network in Docker
  shell:
    cmd: "docker network ls -q --filter='name=^{{ nginx_docker_network }}$'"
  register: nginx_result_docker_network
  changed_when: false

- name: Create Nginx-proxy network in Docker
  shell:
    cmd: "docker network create --driver=bridge {{ nginx_docker_network }}"
  when: "nginx_result_docker_network.stdout == ''"
