---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Nginx-proxy services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ nginx_services_list }}"

- name: Ensure Nginx-proxy services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ nginx_services_list }}"
