---

- name: Ensure Samba image is pulled
  docker_image:
    name: "{{ samba_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Samba paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ samba_base_data_path }}"
    - "{{ samba_data_path }}"

- name: Ensure Samba configured (main config override)
  template:
    src: "{{ role_path }}/templates/samba/config.yml.j2"
    dest: "{{ samba_data_path }}/config.yml"
    mode: 0644

- name: Ensure Samba.service installed
  template:
    src: "{{ role_path }}/templates/samba/samba.service.j2"
    dest: "/etc/systemd/system/samba.service"
    mode: 0644
  register: samba_systemd_service_result

- name: Ensure systemd reloaded after samba.service installation
  service:
    daemon_reload: yes
  when: samba_systemd_service_result.changed