---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Samba services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ samba_services_list }}"

- name: Ensure Samba services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ samba_services_list }}"