---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: pgadmin_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_pgadmin.yml"
  when: pgadmin_installation_enabled|bool == true
  tags:
    - setup-pgadmin
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: pgadmin_installation_enabled|bool == true
  tags:
    - start
