---

- name: Ensure pgAdmin image is pulled
  docker_image:
    name: "{{ pgadmin_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure pgAdmin paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "root"
    group: "root"
  with_items:
    - "{{ pgadmin_data_path }}"

- name: Ensure pgAdmin.service installed
  template:
    src: "{{ role_path }}/templates/pgadmin/pgadmin.service.j2"
    dest: "/etc/systemd/system/pgadmin.service"
    mode: 0644
  register: pgadmin_systemd_service_result

- name: Ensure systemd reloaded after pgAdmin.service installation
  service:
    daemon_reload: yes
  when: pgadmin_systemd_service_result.changed