---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure pgAdmin services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ pgadmin_services_list }}"

- name: Ensure pgAdmin services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ pgadmin_services_list }}"