---

# Base directory that contains everything
samba_base_data_path: "{{ services_base_data_path }}/samba"

# Samba edition
samba_docker_image_template: "ghcr.io/crazy-max/samba:__VERSION__"
samba_docker_image: "{{ samba_docker_image_template|replace('__VERSION__', samba_docker_image_tag) }}"

# Samba-related data
samba_data_path: "{{ samba_base_data_path }}/data"

# Samba global envs
samba_force_user: onlyread
samba_force_group: root

# Samba log level
samba_log_level: 0

# Samba share folders
samba_share_folders: |
  {{
    (['-v /datafolder/sharefolder/public:/samba/public'])
    +
    (['-v /datafolder/sharefolder/media:/samba/media'])
    +
    (['-v /datafolder/mnt:/samba/mnt'])
  }}

# Samba services
samba_services_list: |
  {{
    (['samba.service'])
  }}