---

- name: Ensure Speedtest-Tracker image is pulled
  docker_image:
    name: "{{ speedtest_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Speedtest-Tracker paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ speedtest_data_path }}"

- name: Ensure speedtest.service installed
  template:
    src: "{{ role_path }}/templates/speedtest-tracker/speedtest.service.j2"
    dest: "/etc/systemd/system/speedtest.service"
    mode: 0644
  register: speedtest_systemd_service_result

- name: Ensure systemd reloaded after speedtest.service installation
  service:
    daemon_reload: yes
  when: speedtest_systemd_service_result.changed