---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Speedtest-Tracker services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ speedtest_services_list }}"

- name: Ensure Speedtest-Tracker services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ speedtest_services_list }}"