---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: radarr_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_radarr.yml"
  when: radarr_installation_enabled|bool == true
  tags:
    - setup-radarr
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: radarr_installation_enabled|bool == true
  tags:
    - start
