---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Radarr services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ radarr_services_list }}"

- name: Ensure Radarr services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ radarr_services_list }}"