---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Homepage services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ homepage_services_list }}"

- name: Ensure Homepage services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ homepage_services_list }}"