---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: nextcloud_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_nextcloud.yml"
  when: nextcloud_installation_enabled|bool == true
  tags:
    - setup-nextcloud
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: nextcloud_installation_enabled|bool == true
  tags:
    - start
