---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: tvheadend_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_tvheadend.yml"
  when: tvheadend_installation_enabled|bool == true
  tags:
    - setup-tvheadend
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: tvheadend_installation_enabled|bool == true
  tags:
    - start
