---

- name: Ensure TVheadend image is pulled
  docker_image:
    name: "{{ tvheadend_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure TVheadend paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ tvheadend_data_path }}"

- name: Ensure tvheadend.service installed
  template:
    src: "{{ role_path }}/templates/tvheadend/tvheadend.service.j2"
    dest: "/etc/systemd/system/tvheadend.service"
    mode: 0644
  register: tvheadend_systemd_service_result

- name: Ensure systemd reloaded after tvheadend.service installation
  service:
    daemon_reload: yes
  when: tvheadend_systemd_service_result.changed