---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: planka_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_planka.yml"
  when: planka_installation_enabled|bool == true
  tags:
    - setup-planka
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: planka_installation_enabled|bool == true
  tags:
    - start
