---

- name: Ensure Planka image is pulled
  docker_image:
    name: "{{ planka_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Planka paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: {{ planka_uid }}
    group: {{ planka_gid }}
  with_items:
    - "{{ planka_config_path }}"

- name: Ensure Planka.service installed
  template:
    src: "{{ role_path }}/templates/planka/planka.service.j2"
    dest: "/etc/systemd/system/planka.service"
    mode: 0644
  register: planka_systemd_service_result

- name: Ensure systemd reloaded after planka.service installation
  service:
    daemon_reload: yes
  when: planka_systemd_service_result.changed