---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Planka services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ planka_services_list }}"

- name: Ensure Planka services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ planka_services_list }}"