---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure FileBrowser services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ filebrowser_services_list }}"

- name: Ensure FileBrowser services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ filebrowser_services_list }}"