---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: transmission_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_transmission.yml"
  when: transmission_installation_enabled|bool == true
  tags:
    - setup-transmission
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: transmission_installation_enabled|bool == true
  tags:
    - start
