---

- name: Ensure Transmission image is pulled
  docker_image:
    name: "{{ transmission_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Transmission paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ transmission_data_path }}"

- name: Ensure Transmission.service installed
  template:
    src: "{{ role_path }}/templates/transmission/transmission.service.j2"
    dest: "/etc/systemd/system/transmission.service"
    mode: 0644
  register: transmission_systemd_service_result

- name: Ensure systemd reloaded after transmission.service installation
  service:
    daemon_reload: yes
  when: transmission_systemd_service_result.changed