---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Transmission services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ transmission_services_list }}"

- name: Ensure Transmission services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ transmission_services_list }}"