---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: nexus_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_nexus.yml"
  when: nexus_installation_enabled|bool == true
  tags:
    - setup-nexus
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: nexus_installation_enabled|bool == true
  tags:
    - start
