---

- name: Ensure Nexus image is pulled
  docker_image:
    name: "{{ nexus_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Nexus paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: 200
    group: 200
  with_items:
    - "{{ nexus_data_path }}"

- name: Ensure nexus.service installed
  template:
    src: "{{ role_path }}/templates/nexus/nexus.service.j2"
    dest: "/etc/systemd/system/nexus.service"
    mode: 0644
  register: nexus_systemd_service_result

- name: Ensure systemd reloaded after nexus.service installation
  service:
    daemon_reload: yes
  when: nexus_systemd_service_result.changed