---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: sonarr_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_sonarr.yml"
  when: sonarr_installation_enabled|bool == true
  tags:
    - setup-sonarr
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: sonarr_installation_enabled|bool == true
  tags:
    - start
