---

- name: Ensure Sonarr image is pulled
  docker_image:
    name: "{{ sonarr_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Sonarr paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ sonarr_data_path }}"

- name: Ensure sonarr.service installed
  template:
    src: "{{ role_path }}/templates/sonarr/sonarr.service.j2"
    dest: "/etc/systemd/system/sonarr.service"
    mode: 0644
  register: sonarr_systemd_service_result

- name: Ensure systemd reloaded after sonarr.service installation
  service:
    daemon_reload: yes
  when: sonarr_systemd_service_result.changed