---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Sonarr services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ sonarr_services_list }}"

- name: Ensure Sonarr services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ sonarr_services_list }}"