{
 "title": "SMART HDD|SSD",
 "tags": [ "system" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "SMART Health",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "smartprom_smart_passed" }
   ]
  },
  {
   "title": "Error Metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartprom_reallocated_sector_ct_raw"
    },
    {
     "expr": "smartprom_reported_uncorrect_raw"
    },
    { "expr": "smartprom_command_timeout_raw" },
    {
     "expr": "smartprom_current_pending_sector_raw"
    },
    {
     "expr": "smartprom_offline_uncorrectable_raw"
    }
   ]
  },
  {
   "title": "Info Metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartprom_temperature_celsius_raw"
    },
    {
     "expr": "smartprom_power_cycle_count_raw"
    },
    { "expr": "smartprom_power_on_hours_raw" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "smartprom_temperature_celsius_raw",
     "legendFormat": "{{drive}}"
    }
   ]
  }
 ]
}