---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: jackett_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_jackett.yml"
  when: jackett_installation_enabled|bool == true
  tags:
    - setup-jackett
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: jackett_installation_enabled|bool == true
  tags:
    - start
