---

- name: Ensure Jackett image is pulled
  docker_image:
    name: "{{ jackett_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Jackett paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ jackett_data_path }}"

- name: Ensure jackett.service installed
  template:
    src: "{{ role_path }}/templates/jackett/jackett.service.j2"
    dest: "/etc/systemd/system/jackett.service"
    mode: 0644
  register: jackett_systemd_service_result

- name: Ensure systemd reloaded after jackett.service installation
  service:
    daemon_reload: yes
  when: jackett_systemd_service_result.changed