---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Jackett services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ jackett_services_list }}"

- name: Ensure Jackett services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ jackett_services_list }}"