---

- name: Ensure Prometheus image is pulled
  docker_image:
    name: "{{ prometheus_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Prometheus paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: 65534
    group: 65534
  with_items:
    - "{{ prometheus_data_path }}"
    - "{{ prometheus_config_path }}"

- name: Ensure prometheus.yml config installed
  template:
    src: "{{ role_path }}/templates/prometheus/prometheus.yml.j2"
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    mode: 0644
    owner: 65534
    group: 65534

- name: Ensure prometheus.service installed
  template:
    src: "{{ role_path }}/templates/prometheus/prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
    mode: 0644
  register: prometheus_systemd_service_result

- name: Ensure systemd reloaded after prometheus.service installation
  service:
    daemon_reload: yes
  when: prometheus_systemd_service_result.changed