---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Exporter services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ exporter_services_list }}"

- name: Ensure Exporter services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ exporter_services_list }}"

- name: Ensure Prometheus services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ prometheus_services_list }}"

- name: Ensure Prometheus services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ prometheus_services_list }}"