---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: postgres_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_postgres.yml"
  when: postgres_installation_enabled|bool == true
  tags:
    - setup-postgres
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: postgres_installation_enabled|bool == true
  tags:
    - start
