---

- name: Ensure Postgres image is pulled
  docker_image:
    name: "{{ postgres_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Postgres paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: "999"
    group: "root"
  with_items:
    - "{{ postgres_data_path }}"

- name: Ensure Postgres.service installed
  template:
    src: "{{ role_path }}/templates/postgres/postgres.service.j2"
    dest: "/etc/systemd/system/postgres.service"
    mode: 0644
  register: postgres_systemd_service_result

- name: Ensure systemd reloaded after postgres.service installation
  service:
    daemon_reload: yes
  when: postgres_systemd_service_result.changed