---

- name: Ensure Plex image is pulled
  docker_image:
    name: "{{ plex_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Plex paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ plex_data_path }}"

- name: Ensure Nginx-proxy configured (Plex)
  template:
    src: "{{ role_path }}/templates/conf.d/plex.conf.j2"
    dest: "{{ nginx_proxy_confd_path }}/plex.conf"
    mode: 0644
  register: nginx_proxy_plex_configured_result

- name: Ensure systemd reloaded after plex nginx-proxy configured
  service:
    name: nginx-proxy.service
    state: restarted
  when: nginx_proxy_plex_configured_result.changed

- name: Ensure Plex.service installed
  template:
    src: "{{ role_path }}/templates/plex/plex.service.j2"
    dest: "/etc/systemd/system/plex.service"
    mode: 0644
  register: plex_systemd_service_result

- name: Ensure systemd reloaded after plex.service installation
  service:
    daemon_reload: yes
  when: plex_systemd_service_result.changed