---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Plex services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ plex_services_list }}"

- name: Ensure Plex services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ plex_services_list }}"