---

- import_tasks: "{{ role_path }}/tasks/setup_main.yml"
  when: tubearchivist_installation_enabled|bool == true
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_tubearchivist.yml"
  when: tubearchivist_installation_enabled|bool == true
  tags:
    - setup-tubearchivist
    - setup-all

- import_tasks: "{{ role_path }}/tasks/start.yml"
  when: tubearchivist_installation_enabled|bool == true
  tags:
    - start
