---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure TubeArchivist services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ tubearchivist_services_list }}"

- name: Ensure TubeArchivist services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ tubearchivist_services_list }}"