---

- name: Stop and disable systemd-resolved service
  service:
    name: systemd-resolved
    enabled: no
    state: stopped
  when: pihole_manage_host_resolver | bool

- name: Ensure resolv.conf installed
  template:
    src: "{{ role_path }}/templates/resolv.conf.j2"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: '0644'
  when: pihole_manage_host_resolver | bool
