---

- name: Ensure Pihole image is pulled
  docker_image:
    name: "{{ pihole_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure Pihole paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ pihole_data_path }}"

- name: Ensure Pihole.service installed
  template:
    src: "{{ role_path }}/templates/pihole/pihole.service.j2"
    dest: "/etc/systemd/system/pihole.service"
    mode: 0644
  register: pihole_systemd_service_result

- name: Ensure systemd reloaded after pihole.service installation
  service:
    daemon_reload: yes
  when: pihole_systemd_service_result.changed