---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Pihole services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ pihole_services_list }}"

- name: Ensure Pihole services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ pihole_services_list }}"