---

- name: Ensure MeTube image is pulled
  docker_image:
    name: "{{ metube_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure MeTube paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "root"
    group: "root"
  with_items:
    - "{{ metube_downloads_path }}"

- name: Ensure metube.service installed
  template:
    src: "{{ role_path }}/templates/metube/metube.service.j2"
    dest: "/etc/systemd/system/metube.service"
    mode: 0644
  register: metube_systemd_service_result

- name: Ensure systemd reloaded after metube.service installation
  service:
    daemon_reload: yes
  when: metube_systemd_service_result.changed